from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


TITLE_FILL = "162536"
HEADER_FILL = "10B981"
SECTION_FILL = "DCE8F1"
WHITE = "FFFFFF"
BLACK = "000000"


def style_title_cell(cell):
    cell.font = Font(bold=True, color=WHITE, size=14)
    cell.fill = PatternFill("solid", fgColor=TITLE_FILL)
    cell.alignment = Alignment(horizontal="center")


def style_header_cell(cell):
    cell.font = Font(bold=True, color=BLACK)
    cell.fill = PatternFill("solid", fgColor=HEADER_FILL)
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell.border = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin")
    )


def style_label_cell(cell):
    cell.font = Font(bold=True)
    cell.fill = PatternFill("solid", fgColor=SECTION_FILL)
    cell.alignment = Alignment(vertical="top", wrap_text=True)


def style_value_cell(cell):
    cell.alignment = Alignment(vertical="top", wrap_text=True)


def autosize_columns(ws, min_width=12, max_width=80):
    for column_cells in ws.columns:
        max_length = 0
        column_letter = get_column_letter(column_cells[0].column)

        for cell in column_cells:
            value = cell.value

            if value is None:
                continue

            value_length = len(str(value))

            if value_length > max_length:
                max_length = value_length

        adjusted_width = min(max(max_length + 2, min_width), max_width)
        ws.column_dimensions[column_letter].width = adjusted_width


def freeze_and_filter(ws, freeze_cell="A2"):
    ws.freeze_panes = freeze_cell

    if ws.max_row > 1 and ws.max_column > 1:
        ws.auto_filter.ref = ws.dimensions


def append_key_value_rows(ws, rows):
    for label, value in rows:
        ws.append([label, value])
        style_label_cell(ws.cell(row=ws.max_row, column=1))
        style_value_cell(ws.cell(row=ws.max_row, column=2))


def add_title(ws, title, columns=2):
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=columns)
    cell = ws.cell(row=1, column=1)
    cell.value = title
    style_title_cell(cell)


def add_header_row(ws, headers):
    ws.append(headers)

    for col in range(1, len(headers) + 1):
        style_header_cell(ws.cell(row=ws.max_row, column=col))


def format_bytes(size_bytes):
    if size_bytes is None:
        return "Unknown"

    size = float(size_bytes)

    for unit in ["bytes", "KB", "MB", "GB", "TB"]:
        if size < 1024 or unit == "TB":
            if unit == "bytes":
                return f"{int(size)} {unit}"

            return f"{size:.2f} {unit}"

        size /= 1024

    return f"{size_bytes} bytes"


def save_manifest_xlsx(manifest, xlsx_path):
    wb = Workbook()

    ws_summary = wb.active
    ws_summary.title = "Summary"

    department = manifest.get("department", {})
    case_info = manifest.get("case_info", {})
    hash_settings = manifest.get("hash_settings", {})
    report_options = manifest.get("report_options", {})
    file_summary = manifest.get("file_summary", {})

    add_title(ws_summary, "ByteCase Verify - Hash Manifest Summary", columns=2)

    rows = [
        ("Generated By", f"{manifest.get('app_name', '')} - {manifest.get('app_subtitle', '')} v{manifest.get('app_version', '')}"),
        ("Suite", manifest.get("suite_name", "ByteCase")),
        ("Publisher", manifest.get("publisher", "Forensics Byte")),
        ("Created At", manifest.get("created_at", "")),
        ("Department / Agency", department.get("department_name", "")),
        ("Unit", department.get("unit_name", "")),
        ("Case Number", case_info.get("case_number", "")),
        ("Agency Case Number", case_info.get("agency_case_number", "")),
        ("Exhibit / Item Reference", case_info.get("exhibit_reference", "")),
        ("Technician", case_info.get("technician", "")),
        ("Reviewed By", case_info.get("reviewed_by", "")),
        ("Source Description", case_info.get("source_description", "")),
        ("Algorithms", ", ".join(hash_settings.get("algorithms", []))),
        ("Recursive Folder Selection", "Yes" if hash_settings.get("recursive") else "No"),
        ("Hash Generation Method Included", "Yes" if hash_settings.get("include_hash_generation_method") else "No"),
        ("Hashing Explanation Included", "Yes" if hash_settings.get("include_hashing_explanation") else "No"),
        ("Signature Block Included", "Yes" if report_options.get("include_signature_block") else "No"),
        ("Total Files Listed", file_summary.get("total_files", 0)),
        ("Completed", file_summary.get("completed_count", 0)),
        ("Errors", file_summary.get("error_count", 0)),
        ("Total Size", format_bytes(file_summary.get("total_size_bytes", 0))),
        ("Notes", manifest.get("notes", ""))
    ]

    append_key_value_rows(ws_summary, rows)
    autosize_columns(ws_summary)

    ws_files = wb.create_sheet("Files")
    add_header_row(
        ws_files,
        [
            "File Name",
            "Relative Path",
            "File Path",
            "Size Bytes",
            "Size",
            "Modified Time",
            "MD5",
            "SHA-1",
            "SHA-256",
            "Status",
            "Error"
        ]
    )

    for record in manifest.get("files", []):
        ws_files.append([
            record.get("file_name", ""),
            record.get("relative_path", ""),
            record.get("file_path", ""),
            record.get("file_size_bytes", ""),
            format_bytes(record.get("file_size_bytes")),
            record.get("modified_time", ""),
            record.get("md5") or "Not calculated",
            record.get("sha1") or "Not calculated",
            record.get("sha256") or "Not calculated",
            record.get("hash_status", ""),
            record.get("error", "")
        ])

    freeze_and_filter(ws_files)
    autosize_columns(ws_files)

    error_records = [
        record for record in manifest.get("files", [])
        if record.get("hash_status") == "Error" or record.get("error")
    ]

    ws_errors = wb.create_sheet("Errors")
    add_header_row(ws_errors, ["File Name", "File Path", "Status", "Error"])

    for record in error_records:
        ws_errors.append([
            record.get("file_name", ""),
            record.get("file_path", ""),
            record.get("hash_status", ""),
            record.get("error", "")
        ])

    freeze_and_filter(ws_errors)
    autosize_columns(ws_errors)

    wb.save(xlsx_path)


def save_verification_xlsx(report, xlsx_path):
    wb = Workbook()

    ws_summary = wb.active
    ws_summary.title = "Summary"

    original = report.get("original_manifest", {})
    case_info = original.get("case_info", {})
    summary = report.get("summary", {})

    add_title(ws_summary, "ByteCase Verify - Hash Manifest Verification Summary", columns=2)

    rows = [
        ("Generated By", f"{report.get('app_name', '')} - {report.get('app_subtitle', '')} v{report.get('app_version', '')}"),
        ("Suite", report.get("suite_name", "ByteCase")),
        ("Publisher", report.get("publisher", "Forensics Byte")),
        ("Verification Created At", report.get("verification_created_at", "")),
        ("Technician", report.get("technician", "")),
        ("Algorithms Considered", ", ".join(report.get("algorithms_considered", []))),
        ("Original App", f"{original.get('app_name', '')} v{original.get('app_version', '')}"),
        ("Original Created At", original.get("created_at", "")),
        ("Case Number", case_info.get("case_number", "")),
        ("Agency Case Number", case_info.get("agency_case_number", "")),
        ("Original Technician", case_info.get("technician", "")),
        ("Source Description", case_info.get("source_description", "")),
        ("Total Results", summary.get("total_results", 0)),
        ("Matched", summary.get("matched", 0)),
        ("Hash Mismatch", summary.get("hash_mismatch", 0)),
        ("Missing From Current Selection", summary.get("missing_from_current_selection", 0)),
        ("New File Not In Original Manifest", summary.get("new_file_not_in_original_manifest", 0)),
        ("Errors", summary.get("errors", 0)),
        ("Notes", report.get("notes", ""))
    ]

    append_key_value_rows(ws_summary, rows)
    autosize_columns(ws_summary)

    ws_results = wb.create_sheet("Verification Results")
    add_header_row(
        ws_results,
        [
            "File Name",
            "Status",
            "Detail",
            "Original Path",
            "Current Path",
            "Algorithms Checked",
            "Original MD5",
            "Current MD5",
            "Original SHA-1",
            "Current SHA-1",
            "Original SHA-256",
            "Current SHA-256"
        ]
    )

    for result in report.get("results", []):
        original_hashes = result.get("original_hashes", {})
        current_hashes = result.get("current_hashes", {})

        ws_results.append([
            result.get("file_name", ""),
            result.get("status", ""),
            result.get("detail", ""),
            result.get("original_path", ""),
            result.get("current_path", ""),
            ", ".join(result.get("algorithms_checked", [])),
            original_hashes.get("MD5", ""),
            current_hashes.get("MD5", ""),
            original_hashes.get("SHA-1", ""),
            current_hashes.get("SHA-1", ""),
            original_hashes.get("SHA-256", ""),
            current_hashes.get("SHA-256", "")
        ])

    freeze_and_filter(ws_results)
    autosize_columns(ws_results)

    ws_issues = wb.create_sheet("Issues")
    add_header_row(ws_issues, ["File Name", "Status", "Detail", "Original Path", "Current Path"])

    for result in report.get("results", []):
        if result.get("status") != "Matched":
            ws_issues.append([
                result.get("file_name", ""),
                result.get("status", ""),
                result.get("detail", ""),
                result.get("original_path", ""),
                result.get("current_path", "")
            ])

    freeze_and_filter(ws_issues)
    autosize_columns(ws_issues)

    wb.save(xlsx_path)


def save_compare_xlsx(report, xlsx_path):
    wb = Workbook()

    ws_summary = wb.active
    ws_summary.title = "Summary"

    manifest_a = report.get("manifest_a", {})
    manifest_b = report.get("manifest_b", {})
    case_a = manifest_a.get("case_info", {})
    case_b = manifest_b.get("case_info", {})
    summary = report.get("summary", {})

    add_title(ws_summary, "ByteCase Verify - Hash Manifest Compare Summary", columns=2)

    rows = [
        ("Generated By", f"{report.get('app_name', '')} - {report.get('app_subtitle', '')} v{report.get('app_version', '')}"),
        ("Suite", report.get("suite_name", "ByteCase")),
        ("Publisher", report.get("publisher", "Forensics Byte")),
        ("Compare Created At", report.get("compare_created_at", "")),
        ("Technician", report.get("technician", "")),
        ("Algorithms Considered", ", ".join(report.get("algorithms_considered", []))),
        ("Manifest A Path", manifest_a.get("path", "")),
        ("Manifest A Created At", manifest_a.get("created_at", "")),
        ("Manifest A Case Number", case_a.get("case_number", "")),
        ("Manifest A Source Description", case_a.get("source_description", "")),
        ("Manifest B Path", manifest_b.get("path", "")),
        ("Manifest B Created At", manifest_b.get("created_at", "")),
        ("Manifest B Case Number", case_b.get("case_number", "")),
        ("Manifest B Source Description", case_b.get("source_description", "")),
        ("Total Results", summary.get("total_results", 0)),
        ("Matched", summary.get("matched", 0)),
        ("Hash Mismatch", summary.get("hash_mismatch", 0)),
        ("Only In Manifest A", summary.get("only_in_manifest_a", 0)),
        ("Only In Manifest B", summary.get("only_in_manifest_b", 0)),
        ("Errors", summary.get("errors", 0)),
        ("Notes", report.get("notes", ""))
    ]

    append_key_value_rows(ws_summary, rows)
    autosize_columns(ws_summary)

    ws_results = wb.create_sheet("Compare Results")
    add_header_row(
        ws_results,
        [
            "File Name",
            "Status",
            "Detail",
            "Manifest A Path",
            "Manifest B Path",
            "Algorithms Checked",
            "Manifest A MD5",
            "Manifest B MD5",
            "Manifest A SHA-1",
            "Manifest B SHA-1",
            "Manifest A SHA-256",
            "Manifest B SHA-256"
        ]
    )

    for result in report.get("results", []):
        hashes_a = result.get("manifest_a_hashes", {})
        hashes_b = result.get("manifest_b_hashes", {})

        ws_results.append([
            result.get("file_name", ""),
            result.get("status", ""),
            result.get("detail", ""),
            result.get("manifest_a_path", ""),
            result.get("manifest_b_path", ""),
            ", ".join(result.get("algorithms_checked", [])),
            hashes_a.get("MD5", ""),
            hashes_b.get("MD5", ""),
            hashes_a.get("SHA-1", ""),
            hashes_b.get("SHA-1", ""),
            hashes_a.get("SHA-256", ""),
            hashes_b.get("SHA-256", "")
        ])

    freeze_and_filter(ws_results)
    autosize_columns(ws_results)

    ws_differences = wb.create_sheet("Differences")
    add_header_row(ws_differences, ["File Name", "Status", "Detail", "Manifest A Path", "Manifest B Path"])

    for result in report.get("results", []):
        if result.get("status") != "Matched":
            ws_differences.append([
                result.get("file_name", ""),
                result.get("status", ""),
                result.get("detail", ""),
                result.get("manifest_a_path", ""),
                result.get("manifest_b_path", "")
            ])

    freeze_and_filter(ws_differences)
    autosize_columns(ws_differences)

    wb.save(xlsx_path)